
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import "./globals.css";
import type {Metadata} from "next";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "GRABB",
  description: "Generated by create next app",

};

export default function RootLayout({
  children, 
}: Readonly <{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
          <body className="font-poppins antialiased">
            <div className="flex flex-col min-h-screen">
              <Header />
              <main className="flex-1">{children}</main>
              <Footer />
            </div>
          </body>
      </html>
    </ClerkProvider>
  );
}

